version: '3'
services:
    mongo:
        image: 'mongo'
        environment:
            - MONGO_INITDB_DATABASE=readinglist
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=qwe123
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - 27017-27019:27017-27019
        